from __future__ import annotations

RAG_TRUST_SYSTEM_RECORD = "system_record"
RAG_TRUST_MANAGER_CONFIRMED = "manager_confirmed"
RAG_TRUST_MANAGER_SAVED = "manager_saved"
RAG_TRUST_EXTRACTED_UNCONFIRMED = "extracted_unconfirmed"
RAG_TRUST_RAW_USER_INPUT = "raw_user_input"
RAG_TRUST_ASSISTANT_DRAFT = "assistant_draft"

RAG_TRUST_LEVELS = {
    RAG_TRUST_SYSTEM_RECORD,
    RAG_TRUST_MANAGER_CONFIRMED,
    RAG_TRUST_MANAGER_SAVED,
    RAG_TRUST_EXTRACTED_UNCONFIRMED,
    RAG_TRUST_RAW_USER_INPUT,
    RAG_TRUST_ASSISTANT_DRAFT,
}
